before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ZnbjS11nqc/ilkMBefMu7RtcLMR8Ot9P028edaJvCeL+a3+5eTphpSloSegzSooc6ushftOrp4k9gim+IupMjupxPK70f2ytKnv31Y/j2UNY5vINOu3hbePQuiiSkkt8NLGkD9pq7Q+WnF7sPpQKsyTPIpKGu0jcGzYo4EijPsi01Egjawkn/xuDVBvD5AKngHoFOs4I8lD+Q4Bo7Jj1aHsKMx4H7oZ0OGemdu2qn4eTFDoY/ot6egjAKKV2moAPiUGxFmsG54PPTLc0lUe0tN8rPoXh8JdIBjNJu08nKCASiL2lt3rpzxTHyyIok/5350pf7Kjt7TTc6DJ12wl/KkLYK8AQnyF+Kuy9/NyLpKcrUPQVZoqrG5iH9HUyvuks2wLCl6K9R6Nz1Jx6ZTpjpTA1XY21xMaykrUAT+EscQcgDYVUiZYFbH+Bqd2NMqxSTRDautyZFXq78NmUJRofp7YE+Gr/Rkn65tGdCiUewC+M2qlOuBSWyoZCICbyv3h1DgQhcFl2Is4RIqcXiw09jWscGqcJ8AjQtVYhTZFb3q881rFvDTNDO1f3W1nU/KGoCD/4LFMLSjs+yQs5XUPId6WlEFgp9giOFof+BclpG8pUcX2tW10hO1jsL7AMmHt0MvOmuoLZGD9bNLJYaCDB5PG1Z4q4+gnUT9UswwNdS6s= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
